#!/usr/bin/env bash
# -----------------------------------------------
# This idempotent macOS Bash script installs
# all mac softwareupdates
# -----------------------------------------------

# Exit script on any errors
set -e

echo "Installing all Mac software updates:"

# If there are any updates, install them (manual reboot may be required)
softwareupdate --list 2>&1 | grep 'No new software available' || \
  softwareupdate --install --all

# --- FIN ---
echo '✔'
exit 0
