#!/usr/bin/env bash
# -----------------------------------------------
# This idempotent macOS Bash script installs
# Command Line Tools and Homebrew
# -----------------------------------------------

# Exit script on any errors
set -e

echo "Installing Command Line Tools and Homebrew:"

# XCode is required from App Store
# `xcodebuild -version` is the command to determine if Xcode
# is installed, from...
# https://stackoverflow.com/questions/33732042/check-xcode-version-from-command-line
xcodebuild -version || \
  (echo "FAIL [1] - Xcode must be installed first" ; exit 1)
echo -n '.'

# Install Command Line Tools for Xcode...
xcode-select -p || \
  xcode-select --install
echo -n '.'

# Verify - gcc should be installed with Command Line Tools
gcc --version || \
    (echo "FAIL [2] - Command Line Tools with gcc must be installed" ; exit 1)
echo -n '.'

# Install Homebrew Package Manager..."
# From https://brew.sh/ May 2023
brew help || \
  (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || \
    echo "FAIL [3] - Unable to install Homebrew" ; exit 1)
echo -n '.'

# Add brew shellenv to your ~/.zshrc file"
# This is inside baseball from the brew install script
# Determine where brew itself is installed based on Intel vs Apple Silicon
[[ `uname -m` == "arm64" ]] && homebrew_prefix="/opt/homebrew" || homebrew_prefix="/usr/local"
grep -qs "eval \"\$(${homebrew_prefix}/bin/brew shellenv)\"" ~/.zshrc || \
  (echo; \
  echo '# Add Homebrew package management to shell environment'; \
  echo "eval \"\$(${homebrew_prefix}/bin/brew shellenv)\"") >> ~/.zshrc
echo -n '.'

# --- FIN ---
echo '✔'
exit 0
