#!/usr/bin/env bash
# -----------------------------------------------
# This idempotent macOS Bash script uses
# Homebrew Cask to install basic dev apps...
# - Browsers
#   - Chrome
#   - Firefox
# - Docker Desktop
# - VS Code
# -----------------------------------------------

# Exit script on any errors
set -e

echo "Homebrew installing basic development tools:"
# ADD/CHANGE dev apps here
dev_apps=(
  google-chrome
  firefox
  docker
  visual-studio-code
)

# Homebrew is required
brew help || \
  (echo "FAIL [1] - Homebrew must be installed first" ; exit 1)
echo -n '.'

for app in ${dev_apps[@]}; do
  brew list --cask "$app" || \
    (echo "brew install --cask ${app}"; brew install --cask "$app")
done
echo -n '.'

# --- FIN ---
echo '✔'
exit 0
