#!/usr/bin/env bash

# Exit script on any errors
set -e

usage() {
  cat << EOF
Usage: $(basename $0) [-h]
This idempotent macOS Bash script uses Homebrew to install vim and git
with the Janus vim plugins

OPTIONS:
  -h  display help
EOF
}

while getopts 'h' opt; do
  case "$opt" in
    ?|h)
    usage
    exit
      ;;
  esac
done
shift "$(($OPTIND -1))"

# -- MAIN --
echo "Homebrew installing git and vim with janus extensions:"
dev_tools=(
  git
  vim
)

# Homebrew is required
brew help > /dev/null || \
  (echo "FAIL [1] - Homebrew must be installed first" ; exit 1)

# Install dev tools
for tool in ${dev_tools[@]}; do
  brew list "$tool" > /dev/null || \
    (echo "brew install ${tool}"; brew install "$tool")
done

# Install Janus vim plugins
# Install script from https://github.com/carlhuda/janus
# Checking if Janus is already installed from the install script
# https://github.com/carlhuda/janus/blob/master/bootstrap.sh
test -e ~/.vim/janus || \
  (echo "Installing Janus" ; curl -L https://bit.ly/janus-bootstrap | bash)

# Disable tlib plugin for E1208: error
grep "call janus#disable_plugin('tlib')" ~/.vimrc.before > /dev/null || \
  (echo "call janus#disable_plugin('tlib')") >> ~/.vimrc.before
